config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :users
  resources :logs
  root to: 'logs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord

  belongs_to :user
  before_create :register_date

  scope :recent, -> { order(date: :desc)}


  private

  def register_date
    self.date = DateTime.now
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :logs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



private

  def require_current_user
    unless logged_in?
      redirect_to new_session_path, notice: 'You need to log in...'
    end
  end

  def logged_in?
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :logged_in?

end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :require_current_user
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    @logs = @current_user.logs.recent.limit(10)
    @log = Log.new(systolic: Log.last&.systolic || 120, diastolic: Log.last&.diastolic || 90, heart_rate: Log.last.heart_rate || 72)
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new(systolic: Log.last&.systolic || 120, diastolic: Log.last&.diastolic || 90)
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)
    @log.user = @current_user

    respond_to do |format|
      if @log.save
        format.html { redirect_to logs_path, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to logs_path, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = @current_user.logs.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:systolic, :diastolic, :date, :heart_rate, :notes)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
    redirect_to new_session_path, notice: flash[:notice]
  end

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash[:notice] = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arpcentral // Bpress</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="row align-items-center">
      <div class="col col-6">
        <img src="/img/bpress-icon-grey.png">
      </div>
      <div class="col col-5">
        <h1>BPress</h1>
      </div>
    </nav>


    <div class="row m-1">
      <div class="col-sm-12">
      <main>
        <% if flash[:notice] %>
          <div class="row">
            <div class="col-12 text-center">
              <div class="alert alert-warning" role="alert">
              <%= flash[:notice] %>

              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>


              </div>
            </div>
          </div>
        <% end %>
        <%= yield %>
      </main>
      </div>
    </div>


    <footer class="row">
      <div class="col-sm-12">
        <p> v1.0 | Arpcentral.net </p>


          <% if logged_in? %>
            <%= link_to fa_icon("sign-out-alt", text: "Sign Out"), session_path('whatevs'), method: :delete %>
          <% else %>
            <%= link_to fa_icon("sign-in-alt", text: "Sign In"), new_session_path %>
          <% end %>


      </div>
    </footer>
  </body>
</html>

app/views/logs/_form.html.erb
<div class="row">
  <div class="col col-12">
    <h2>Take a Measurement</h2>
  </div>
</div>

<%= form_with(model: log, local: true) do |form| %>

  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<div class="row align-items-center m-1 mb-4">

 <div class="col col-4 col-md-3">
    Systolic
  </div>

  <div class="col col-1 text-center" >

  </div>

  <div class="col col-4 col-md-3">
    Dystolic
  </div>

    <div class="col col-3 col-md-3">
    Pulse
  </div>


  <div class="col col-4 col-md-3">
    <%= form.number_field :systolic, placeholder: 'Systolic', class: 'form-control form-control-lg' %>
  </div>

  <div class="col col-1 text-center" >
    /
  </div>

  <div class="col col-4 col-md-3">
    <%= form.number_field :diastolic, placeholder: 'Diastolic', class: 'form-control form-control-lg' %>
  </div>

    <div class="col col-3 col-md-3">
    <%= form.number_field :heart_rate, placeholder: 'Rate', class: 'form-control form-control-lg' %>
  </div>
</div>

<div class="row align-items-center m-1 mb-4">
  <div class="col-12 mt-2 mt-md-0">
    <%= form.label :notes %>
    <%= form.text_area :notes, class: 'form-control form-control-lg' %>
  </div>
</div>


<div class="row align-items-center m-1 mb-4">
  <div class="col-12 mt-2 mt-md-0">
    <%= form.submit class: 'btn btn-lg btn-success btn-block' %>
  </div>
</div>


<% end %>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<%= render 'form', log: @log %>


<div class="row">
  <div class="col col-12">
    <h2>Past Measurements</h2>
  </div>
</div>

<div class="row">
  <div class="col col-10 offset-1">
    <table class="table">
      <tbody>
        <% @logs.each do |log| %>
          <tr class="log-record">
            <td width="35%">
              <%= link_to log do %>
                <%= log.systolic %>/<%= log.diastolic %>
                <%= "(#{log.heart_rate})" if log.heart_rate.present? %>
                <% end %>
            </td>
            <td><%= fa_icon('comment', title: log.notes) if log.notes.present? %></td>
            <td width="45%"><%= log.date.strftime('%m/%d %l:%M %P') %></td>
            <td nowrap="nowrap">
              <p class="btn-group">

              </p>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/logs/new.html.erb
<h1>Log a New Reading</h1>
<%= render 'form', log: @log %>

app/views/logs/show.html.erb
<div class="row m-1">
  <div class="col col-12  m-1">
    <h2>
      <%= @log.systolic %> /
      <%= @log.diastolic %>
    </h2>
  <% if @log.heart_rate.present? %>
    <p>
      <strong>Pulse:</strong>
      <%= @log.heart_rate %>
    </p>
  <% end %>
  <p>
    <strong>Date:</strong>
    <%= @log.date %>
  </p>

  </div>

  <div class="col-12 btn-group m-1">
    <%= link_to fa_icon("reply", text: "Return"), logs_path, class: 'btn btn-lg btn-secondary' %>
    <%= link_to fa_icon("edit", text: "Update") , edit_log_path(@log), class: 'btn btn-lg btn-info' %>
    <%= link_to fa_icon("remove", text: "Remove"), @log, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-lg btn-danger' %>

  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>